### ISSUE TITLE
Please add README.

### ISSUE THREAD

**Issue by tarik817** [rosemspace/rosemspace.github.io#1]
Really want to know what is going on here :)

**Comment by roshecode** [comment]
@tarik817 the `master` branch is used for content serving purpose only and therefor not supposed to contain a `README.md` file. However, you can find the basic `README.md` [here](https://github.com/rosemspace/rosemspace.github.io/tree/dev). More info will be added there as soon as I will have free time 😃 

UPD: I'll move that `README.md` from `dev` branch to `master` later as it's really better to have it on the main page 😉
